config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    # Any extra routes for devise users
  end

  root 'home#index'
  get '/contact', to: 'home#contact'
  get '/about-us', to: 'home#about'
  get '/change_role', to: 'change_roles#change_role'

  get '/job_requests/search' => 'job_requests#search', as: "search_job_requests"
  #post '/job_offers/:id/accept'  =>  'job_offers#accept', as: "accept_job_offer"
  resources :jobs do
    resources :tasks, except: [:show, :index]
  end

  resources :job_requests do
    member do
      get 'view_offers', to: 'job_offers#index', as: 'view_offers'
    end
  end

  resources :job_requests

  ####----Below is accepting job offer---
  resources :job_offers do
    member do
      post 'accept', to: 'job_offers#accept', as: 'accept'
    end
  end


  #resources :customers
  resources :contractors, :only => [:create, :delete, :index]
  resources :customers, :only => [:create, :delete]
  get '/customers' => 'customers#dashboard', as: "customer_dashboard"
  #resources :contractors, :only => [:create, :delete]
  get '/contractor/edit' => 'contractors#edit', as: "edit_contractor"
  put '/contractor/update' => 'contractors#update', as: "update_contractor"
  resources :contractors
  resources :notifications, only: [:index] do
    member do
      put :toggle_read_status
      put :hide
    end
  end
end

app/models/job.rb
class Job < ActiveRecord::Base

  include ActiveModel::Validations

  validates :name, :presence => true

  validates :description, :presence => true

  validates :location, :presence => true

  validates :start_date, :presence => true

  validates :end_date, :presence => true

  belongs_to :contractor
  belongs_to :customer
  has_many :tasks
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    #@jobs = Job.all
    @jobs = current_user.contractor.jobs.all
    @completed_jobs = current_user.contractor.jobs.where(completed: false)
    @ongoing_jobs = current_user.contractor.jobs.where(completed: true)
  end

  def new
    @job = Job.new
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.create(job_params)
    if @job.valid?
      flash[:notice] = "#{@job.name} was successfully created."
      @job.contractor= current_user.contractor
      @job.save
      redirect_to @job
    else
      #puts @job.errors.full_messages
      #redirect_to new_job_path(@job)
      render :new
    end
  end

  def update
    @job = Job.find(params[:id])
    puts params[:completed]

    if @job.update(job_params)
      flash[:notice] = "The job was successfully updated"
      redirect_to @job
    else
      render 'edit'
    end
  end

  def show
    @job = Job.find(params[:id])
    @tasks = @job.tasks.all unless @job.nil?
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:notice] = "The job was successfully deleted"
    redirect_to jobs_path
  end

  private
  def job_params
    params.require(:job).permit(:name, :description, :location, :start_date, :end_date, :completed)
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_job.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"> <%= job.name %> </h3>
  </div>
  <div class="panel-body ">
    <b>Location:</b> <%= job.location %>
    <br>
    <b>Description: </b> <%= job.description %>
  </div>
</div>

app/views/jobs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-4 col-sm-4 col-sm-offset-4">

      <h1>Edit job</h1>

      <%= bootstrap_form_for(@job, label_errors: true, url: job_path(@job), method: :patch) do |f| %>
          <%= f.text_field :name %>
          <%= f.text_area :description %>
          <%= f.text_field :location %>
          <%= f.date_field :start_date %>
          <%= f.date_field :end_date %>
          <%= f.form_group :ongoing do %>
              <%= f.check_box :completed, label: "Check this box if the job is completed" %>
          <% end %>
          <%= f.submit "Submit Job Changes", id: "editjob", class: "btn btn-primary" %>
      <% end %>
      <br>
      <%= link_to 'New Task', new_job_task_path(@job.id), id: 'new_task', class: 'btn btn-sm btn-success' %>

    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="text-center">
        <%= bootstrap_form_tag(label_errors: true, url: search_job_requests_path, :method => :get) do |f| %>
            <%= f.text_field :q, label: "Search Job Requests", id: "search_job_request_field", autofocus: true, required: true %>
            <%= f.submit "Search", class: "btn btn-primary", id: "search_job_requests" %>
        <% end %>
      </div>
      <br><br><br>

      <ul class="nav nav-tabs tabs-up" id="friends">
        <li class="active">
          <a href="#" data-target="#ongoing_jobs" id="ongoing_jobs_tab" data-toggle="tabajax" rel="tooltip"> Ongoing
            Jobs </a></li>
        <li><a href="#" data-target="#completed_jobs" id="completed_jobs_tab" data-toggle="tabajax" rel="tooltip">
          Completed Jobs </a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane fade-in active" id="ongoing_jobs">
          <div class="container">
            <div class="row">
              <div class="col-sm-12">
                <table class="table table-striped">
                  <caption>Click on a job name to view or edit it</caption>
                  <thead>
                  <tr>
                    <th>Job Name</th>
                    <th>Location</th>
                    <th>Description</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @completed_jobs.each do |job| %>
                      <tr>
                        <td><%= link_to "#{job.name}", job_path(job.id), id: "job_#{job.id}" %></td>
                        <td><%= job.location %></td>
                        <td><%= job.description %></td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>
                <%= link_to 'Create a job', new_job_path %>
              </div>
            </div>
          </div>
        </div>
        <div class="tab-pane" id="completed_jobs">
          <div class="container">
            <div class="row">
              <div class="col-sm-12">
                <table class="table table-striped">
                  <caption>Click on a job name to view or edit it222</caption>
                  <thead>
                  <tr>
                    <th>Job Name</th>
                    <th>Location</th>
                    <th>Description</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @ongoing_jobs.each do |job| %>
                      <tr>
                        <td><%= link_to "#{job.name}", job_path(job.id), id: "job_#{job.id}" %></td>
                        <td><%= job.location %></td>
                        <td><%= job.description %></td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>
                <%= link_to 'Create a job', new_job_path %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $('[data-toggle="tabajax"]').click(function (e) {
    var $this = $(this);
    $this.tab('show');
    return false;
  });

</script>

app/views/jobs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-offset-4 col-xs-4 col-xs-offset-4">

      <h1>Create job</h1>


      <%= bootstrap_form_for(@job, label_errors: true, url: jobs_path, method: :post) do |f| %>
          <%= f.text_field :name %>
          <%= f.text_area :description %>
          <%= f.text_field :location %>
          <%= f.date_field :start_date %>
          <%= f.date_field :end_date %>
          <%= f.submit "Create", id: "createjob", class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-4 col-sm-4 col-sm-offset-4">
      <br><br><br>

      <h4>
        <strong>Job Title:</strong>
        <%= @job.name %>
      </h4>

      <h4>
        <strong>Job Description:</strong>
        <%= @job.description %>
      </h4>

      <h4>
        <strong>Job Location:</strong>
        <%= @job.location %>
      </h4>

      <h4>
        <strong>Start Date:</strong>
        <%= @job.start_date %>
      </h4>

      <h4>
        <strong>End Date:</strong>
        <%= @job.end_date %>
      </h4>

      <h4>
        <strong>Completed:</strong>
        <% if @job.completed %>
            <i class="fa fa-1x fa-check-square" aria-hidden="true"></i>
        <% else %>
            <i class="fa fa-1x fa-times" aria-hidden="true"></i>
        <% end %>
      </h4>

      <div>
        <h4><strong>Tasks for this job:</strong></h4>
        <% if @tasks.empty? %>
            You do not have any tasks, create one <%= link_to 'here', new_job_task_path(@job) %>
        <% else %>
            <ul class="list-group">
              <% @tasks.each do |task| %>
                  <li class="list-group-item">
                    <div class="pull-right">
                      <%= link_to 'Edit', edit_job_task_path(@job.id, task.id), id: "edit_#{task.id}" %>
                    </div>
                    <strong>Title:</strong> <%= task.title %>
                    <br>
                    <strong>Description:</strong> <%= task.description %>
                    <br>
                    <strong>Completed:</strong> <%= content_tag :i, '', class: ((task.completed) ? 'fa fa-1x fa-check-square' : 'fa fa-1x fa-times'), id: "task_#{task.id}" %>
                    <br>
                    <strong>Duration:</strong> (in minutes) <%= task.duration %>
                  </li>
              <% end %>
            </ul>

        <% end %>
      </div>
      <br>
      <%= link_to 'Back to all jobs', jobs_path, class: 'btn btn-xs btn-back' %>
      <%= link_to 'Edit job', edit_job_path(@job), class: 'btn btn-xs btn-primary' %>
      <%= link_to 'Delete this job', job_path(@job),
                  method: :delete,
                  data: {confirm: 'Are you sure?'}, class: 'btn btn-xs btn-danger' %>
    </div>
  </div>
</div>