config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    # Any extra routes for devise users
  end

  root 'home#index'
  get '/contact', to: 'home#contact'
  get '/about-us', to: 'home#about'
  get '/change_role', to: 'change_roles#change_role'

  get '/job_requests/search' => 'job_requests#search', as: "search_job_requests"
  #post '/job_offers/:id/accept'  =>  'job_offers#accept', as: "accept_job_offer"
  resources :jobs do
    resources :tasks, except: [:show, :index]
  end

  resources :job_requests do
    member do
      get 'view_offers', to: 'job_offers#index', as: 'view_offers'
    end
  end

  resources :job_requests

  ####----Below is accepting job offer---
  resources :job_offers do
    member do
      post 'accept', to: 'job_offers#accept', as: 'accept'
    end
  end


  #resources :customers
  resources :contractors, :only => [:create, :delete, :index]
  resources :customers, :only => [:create, :delete]
  get '/customers' => 'customers#dashboard', as: "customer_dashboard"
  #resources :contractors, :only => [:create, :delete]
  get '/contractor/edit' => 'contractors#edit', as: "edit_contractor"
  put '/contractor/update' => 'contractors#update', as: "update_contractor"
  resources :contractors
  resources :notifications, only: [:index] do
    member do
      put :toggle_read_status
      put :hide
    end
  end
end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
  belongs_to :user
  has_many :jobs
  has_many :job_offers
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :user
  has_many :job_requests

  # This association is here to link customers to their ongoing/completed
  # jobs.  When job offer is accepted, the job will be created with
  # customer_id = current_user.customer.id
  # contractor_id = contractor who made the job offer
  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base

  include ActiveModel::Validations

  validates :name, :presence => true

  validates :description, :presence => true

  validates :location, :presence => true

  validates :start_date, :presence => true

  validates :end_date, :presence => true

  belongs_to :contractor
  belongs_to :customer
  has_many :tasks
end

app/models/job_offer.rb
class JobOffer < ActiveRecord::Base

  validates :title, :presence => true
  validates :description, :presence => true
  validates :hourly_rate, :presence => true


  belongs_to :contractor
  belongs_to :job_request
end

app/models/job_request.rb
class JobRequest < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  validates :title, :presence => true
  validates :description, :presence => true
  validates :location, :presence => true
  validates :hourly_rate, :presence => true
  validates :categories, :presence => true

  belongs_to :customer
  has_many :job_offers

  if Rails.env == 'test'
    index_name("test_job_requests")
  else
    index_name("not-test_job_requests")
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  validates :message, :user, presence: true
  validates :notification_for, presence: true, format: {with: /\A(customer|contractor)\z/, message: "is invalid, choose from 'customer' or 'contractor'"}
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :job
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :first_name, :last_name, :role, presence: true

  has_one :customer
  has_one :contractor
  has_many :notifications

  after_create :create_customer_contractor_or_both

  private

  def create_customer_contractor_or_both
    case self.role
      when "customer"
        self.customer = Customer.create()
        self.save
      when "contractor"
        self.contractor = Contractor.create()
        self.save
      when "both"
        self.customer = Customer.create()
        self.contractor = Contractor.create()
        # In this case default to customer role
        self.role = "customer"
        self.save
      else
        # Just default to a customer 
        self.customer = Customer.create()
        self.role = "customer"
        self.save
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  #leading to dashboard according to the role
  def index
    if user_signed_in?
      if current_user.role == "customer"
        redirect_to customer_dashboard_path
      elsif current_user.role == "contractor"
        redirect_to contractors_path
      end
    else
      render :index
    end
  end

  def contact
  end

  def about
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    #@jobs = Job.all
    @jobs = current_user.contractor.jobs.all
    @completed_jobs = current_user.contractor.jobs.where(completed: false)
    @ongoing_jobs = current_user.contractor.jobs.where(completed: true)
  end

  def new
    @job = Job.new
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.create(job_params)
    if @job.valid?
      flash[:notice] = "#{@job.name} was successfully created."
      @job.contractor= current_user.contractor
      @job.save
      redirect_to @job
    else
      #puts @job.errors.full_messages
      #redirect_to new_job_path(@job)
      render :new
    end
  end

  def update
    @job = Job.find(params[:id])
    puts params[:completed]

    if @job.update(job_params)
      flash[:notice] = "The job was successfully updated"
      redirect_to @job
    else
      render 'edit'
    end
  end

  def show
    @job = Job.find(params[:id])
    @tasks = @job.tasks.all unless @job.nil?
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:notice] = "The job was successfully deleted"
    redirect_to jobs_path
  end

  private
  def job_params
    params.require(:job).permit(:name, :description, :location, :start_date, :end_date, :completed)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :restrict_to_contractors, :retrieve_job

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.valid?
      @task.job = @job
      @task.save
      flash[:notice] = "#{@task.title} successfully created"
      redirect_to edit_job_path(@job)
    else
      render :new
    end
  end

  def edit
    @task = Task.find_by(id: params[:id])
    if @job.contractor != current_user.contractor
      flash[:alert] = "You do not have permission to perform this action"
      redirect_to root_path
    end
  end

  def update
    @task = Task.find_by(id: params[:id])
    if @job.contractor != current_user.contractor
      flash[:alert] = "You do not have permission to perform this action"
      redirect_to root_path
    end
    if not @task.nil? and @task.update(task_params)
      flash[:notice] = "Task successfully updated"
      redirect_to job_path(@job)
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find_by(id: params[:id])
    path = edit_job_path(@job)
    if @job.contractor != current_user.contractor
      flash[:alert] = "You do not have permission to perform this action"
      path = root_path
    end
    @task.destroy
    flash[:notice] = "#{@task.title} successfully deleted"
    redirect_to path
  end

  private
  def task_params
    params.require(:task).permit(:title, :description, :duration, :completed)
  end

  def restrict_to_contractors
    if current_user.role != 'contractor'
      flash[:alert] = 'You do not have permission to be here, switch to your contractor account and try again'
      redirect_to root_path
    end
  end

  def retrieve_job
    @job = Job.find_by(id: params[:job_id])
    if @job.nil?
      flash[:alert] = "Invalid job id #{params[:job_id]}"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_offers_helper.rb
module JobOffersHelper
end

app/helpers/job_requests_helper.rb
module JobRequestsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/partials/_flash_notifications.html.erb
<% if not flash.empty? %>
    <% flash.each do |type, msg| %>
        <script type="text/javascript">
          var duration = parseInt('<%= msg.length %>');
          duration = (duration >= 100) ? 6000 : 4000;
          noty({
            theme: 'bootstrapTheme',
            type: '<%= type %>',
            text: '<%= msg %>',
            layout: 'topRight',
            timeout: duration,
            force: true,
            closeWith: ['click', 'button']
          });
        </script>
    <% end %>
<% end %>

app/views/partials/_footer.html.erb
<footer class="footer">
  <ol class="breadcrumb breadcrumb-footer text-center">
    <li
    <% if action_name == "about" %>class="active"
    <% end %>>
      <% if action_name == "about" %>About
      <% else %><a id="about_us" href="<%= about_us_path %>">About</a>
      <% end %></li>
    <li
    <% if action_name == "contact" %>class="active"
    <% end %>>
      <% if action_name == "contact" %>Contact
      <% else %><a id="contact_us" href="<%= contact_path %>">Contact</a>
      <% end %></li>
  </ol>
</footer>

app/views/partials/_job_request.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"> <%= request.title %> </h3>
  </div>
  <div class="panel-body">
    <b>Description:</b> <%= request.description %>
    <br>
    <b>Location:</b> <%= request.location %>
    <br>
    <b>Rate: </b> <%= request.hourly_rate %>
    <br>
    <b>Catagories: </b> <%= request.catagories %>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Hourli</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse" aria-expanded="false">
      <ul class="nav navbar-nav navbar-right">
        <% if not user_signed_in? %>
            <%= form_tag user_session_path, method: :post, class: "navbar-form" do %>
                <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <%= email_field_tag :email, nil, class: "form-control input-sm", name: "user[email]", id: "user_email_navbar", placeholder: "Email", validate: true, required: true %>
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="fa fa-lock"></i>
                    </div>
                    <%= password_field_tag :password, nil, class: "form-control input-sm", name: "user[password]", id: "user_password_navbar", placeholder: "Password", validate: true, required: true %>
                  </div>
                </div>
                <%= submit_tag "Login", id: "login_navbar", class: "btn btn-default btn-sm" %>
            <% end %>
        <% else %>
            <li class="dropdown">
              <%= link_to notifications_path, remote: true, id: 'notification_dropdown', class: 'dropdown-toggle', role: 'button', data: {target: '#', toggle: 'dropdown'} do %>
                  <i id="notification_bell" data-url="<%= notifications_path %>" data-poll-interval="<%= Rails.configuration.x.poll_interval %>" class="fa fa-lg fa-bell-o"></i>
                  <span id="notification_badge" class="badge notification notification-bell"><%= session[:unread_notification_count] if session[:unread_notification_count] %></span>
              <% end %>

              <ul class="dropdown-menu navbar-dropdown" aria-labelledby="notification_dropdown">
                <span id="notification_content"></span>
                <li class="dropdown-header text-center">
                  <a id="all_messages_link" class="all-messages" href="<%= notifications_path %>">View all messages</a>
                </li>
              </ul>
            </li>

            <li class="navbar-text">
              Viewing as:&nbsp;<%= current_user.role.capitalize %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if current_user.customer and current_user.contractor %>
                    <li>
                      <%= link_to change_role_path, remote: true, id: 'change_role_btn' do %>
                          <%= icon('refresh') %>&nbsp;Change role to&nbsp;
                          <% if current_user.role == 'contractor' %>customer
                          <% else %>contractor
                          <% end %>
                      <% end %>
                    </li>
                <% end %>
                <li>
                  <%= link_to edit_user_registration_path do %>
                      <%= icon('cog') %>&nbsp;<%= current_user.email %>
                  <% end %>
                </li>
                <% if current_user.role == "contractor" %>
                    <li>
                      <%= link_to edit_contractor_path do %>
                          <%= icon('cog') %>&nbsp;Edit Contractor Profile
                      <% end %>
                    </li>
                <% end %>
                <li class="divider"></li>
                <li>
                  <%= link_to destroy_user_session_path, :method => 'delete' do %>
                      <%= icon('power-off') %>&nbsp;Logout
                  <% end %>
                </li>
              </ul>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>