config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    # Any extra routes for devise users
  end

  root 'home#index'
  get '/contact', to: 'home#contact'
  get '/about-us', to: 'home#about'
  get '/change_role', to: 'change_roles#change_role'

  get '/job_requests/search' => 'job_requests#search', as: "search_job_requests"
  #post '/job_offers/:id/accept'  =>  'job_offers#accept', as: "accept_job_offer"
  resources :jobs do
    resources :tasks, except: [:show, :index]
  end

  resources :job_requests do
    member do
      get 'view_offers', to: 'job_offers#index', as: 'view_offers'
    end
  end

  resources :job_requests

  ####----Below is accepting job offer---
  resources :job_offers do
    member do
      post 'accept', to: 'job_offers#accept', as: 'accept'
    end
  end


  #resources :customers
  resources :contractors, :only => [:create, :delete, :index]
  resources :customers, :only => [:create, :delete]
  get '/customers' => 'customers#dashboard', as: "customer_dashboard"
  #resources :contractors, :only => [:create, :delete]
  get '/contractor/edit' => 'contractors#edit', as: "edit_contractor"
  put '/contractor/update' => 'contractors#update', as: "update_contractor"
  resources :contractors
  resources :notifications, only: [:index] do
    member do
      put :toggle_read_status
      put :hide
    end
  end
end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
  belongs_to :user
  has_many :jobs
  has_many :job_offers
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController

  def index
    @jobs = current_user.contractor.jobs.all
    @completed_jobs = current_user.contractor.jobs.where(completed: false)
    @ongoing_jobs = current_user.contractor.jobs.where(completed: true)
  end

  def create
    current_user.contractor = Contractor.create()
    redirect_to edit_user_registration_path
  end

  def edit
    @contractor = current_user.contractor
  end

  def update
    puts params.inspect
    contractor = current_user.contractor
    contractor.update(contractor_params)
    if contractor.save
      flash[:notice] = "Successfully updated contractor profile!"
      redirect_to edit_contractor_path
    else
      flash[:error] = contractor.errors.first
      redirect_to edit_contractor_path
    end
  end

  private
  def contractor_params
    params.require(:contractor).permit(:occupation, :location, :summary)
  end
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/views/contractors/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-offset-4 col-xs-4 col-xs-offset-4">
      <br>
      <h2 class="text-center">Edit Contractor</h2>
      <br>

      <%= bootstrap_form_for(@contractor, label_errors: true, url: update_contractor_path, html: {method: :put}) do |f| %>
          <%= f.text_field :occupation, :value => @contractor.occupation %>
          <%= f.text_field :location, :value => @contractor.location %>
          <%= f.text_area :summary, :value => @contractor.summary %>
          <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/contractors/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="text-center">
        <%= bootstrap_form_tag(label_errors: true, url: search_job_requests_path, :method => :get) do |f| %>
            <%= f.text_field :q, label: "Search Job Requests", id: "search_job_request_field", autofocus: true, required: true %>
            <%= f.submit "Search", class: "btn btn-primary", id: "search_job_requests" %>
        <% end %>
      </div>
      <br><br><br>

      <ul class="nav nav-tabs tabs-up" id="friends">
        <li class="active">
          <a href="#" data-target="#ongoing_jobs" id="ongoing_jobs_tab" data-toggle="tabajax" rel="tooltip"> Ongoing
            Jobs </a></li>
        <li><a href="#" data-target="#completed_jobs" id="completed_jobs_tab" data-toggle="tabajax" rel="tooltip">
          Completed Jobs </a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane fade-in active" id="ongoing_jobs">
          <div class="container">
            <div class="row">
              <div class="col-sm-12">
                <table class="table table-striped">
                  <caption>Click on a job name to view or edit it</caption>
                  <thead>
                  <tr>
                    <th>Job Name</th>
                    <th>Location</th>
                    <th>Description</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @completed_jobs.each do |job| %>
                      <tr>
                        <td><%= link_to "#{job.name}", job_path(job.id), id: "job_#{job.id}" %></td>
                        <td><%= job.location %></td>
                        <td><%= job.description %></td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>
                <%= link_to 'Create a job', new_job_path %>
              </div>
            </div>
          </div>
        </div>
        <div class="tab-pane" id="completed_jobs">
          <div class="container">
            <div class="row">
              <div class="col-sm-12">
                <table class="table table-striped">
                  <caption>Click on a job name to view or edit it</caption>
                  <thead>
                  <tr>
                    <th>Job Name</th>
                    <th>Location</th>
                    <th>Description</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @ongoing_jobs.each do |job| %>
                      <tr>
                        <td><%= link_to "#{job.name}", job_path(job.id), id: "job_#{job.id}" %></td>
                        <td><%= job.location %></td>
                        <td><%= job.description %></td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>
                <%= link_to 'Create a job', new_job_path %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $('[data-toggle="tabajax"]').click(function (e) {
    var $this = $(this);
    $this.tab('show');
    return false;
  });

</script>